server.domain=${SERVER_DOMAIN}}

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASS}
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver

spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update

gcp.projectId=${KEY_NAME}
google.cloud.credentials.base64key=${KEY_VALUE}
google.cloud.storage.bucketName=${BUCKET_NAME}